# TYL Framework Standard Rust Formatting Configuration

# Basic formatting
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
newline_style = "Unix"

# Import and use statement formatting
reorder_imports = true
reorder_modules = true

# Array and expression formatting
array_width = 80
fn_call_width = 80
attr_fn_like_width = 70
struct_lit_width = 60
chain_width = 60

# Line breaking
single_line_if_else_max_width = 50
force_explicit_abi = true